"""added new column rrc in matched product model

Revision ID: 20bb2ad3b92a
Revises: 11d600cbfc22
Create Date: 2023-03-17 21:45:51.533456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20bb2ad3b92a'
down_revision = '11d600cbfc22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matched_products', sa.Column('rrc', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matched_products', 'rrc')
    # ### end Alembic commands ###
