"""control migrations 

Revision ID: 761acfaa9b9b
Revises: f845e149a24a
Create Date: 2023-03-07 16:57:34.891320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761acfaa9b9b'
down_revision = 'f845e149a24a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
