"""added brand columns in matched models

Revision ID: c283a920abdb
Revises: 5e14dce8eea0
Create Date: 2023-03-08 17:36:53.730632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c283a920abdb'
down_revision = '5e14dce8eea0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child_matched_products', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('child_matched_products', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('matched_products', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('matched_products', sa.Column('brand_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matched_products', 'brand_id')
    op.drop_column('matched_products', 'brand')
    op.drop_column('child_matched_products', 'brand_id')
    op.drop_column('child_matched_products', 'brand')
    # ### end Alembic commands ###
