"""added new columns in matched product models and added new model

Revision ID: cccfb4f47228
Revises: 06e8c7b80db0
Create Date: 2023-03-06 20:11:27.808412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cccfb4f47228'
down_revision = '06e8c7b80db0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('min_step', sa.Integer(), nullable=True),
    sa.Column('is_included_to_pm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('child_matched_products', sa.Column('title', sa.String(), nullable=True))
    op.add_column('child_matched_products', sa.Column('vendor_code', sa.String(), nullable=True))
    op.add_column('matched_products', sa.Column('title', sa.String(), nullable=True))
    op.add_column('matched_products', sa.Column('subj_name', sa.String(), nullable=True))
    op.add_column('matched_products', sa.Column('subj_root_name', sa.String(), nullable=True))
    op.add_column('matched_products', sa.Column('vendor_code', sa.String(), nullable=True))
    op.add_column('matched_products', sa.Column('min_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matched_products', 'min_price')
    op.drop_column('matched_products', 'vendor_code')
    op.drop_column('matched_products', 'subj_root_name')
    op.drop_column('matched_products', 'subj_name')
    op.drop_column('matched_products', 'title')
    op.drop_column('child_matched_products', 'vendor_code')
    op.drop_column('child_matched_products', 'title')
    op.drop_table('brands')
    # ### end Alembic commands ###
