"""changed columns and added new ones

Revision ID: f845e149a24a
Revises: cccfb4f47228
Create Date: 2023-03-06 20:27:42.047051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f845e149a24a'
down_revision = 'cccfb4f47228'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child_matched_products', sa.Column('vendor_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child_matched_products', 'vendor_name')
    # ### end Alembic commands ###
